version: '3.3'

networks:
  bridge-network:
    driver: bridge

services:

  openldap-server:
    build:
      context: openldap
    environment:
      LDAP_ADMIN_PASSWORD: D1Wt#s5BAi7L
      LDAP_BASE_DN: dc=byteworks,dc=com
    networks:
      - bridge-network
    ports:
      - 389:389
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

  gateway-service:
    build:
      context: gateway-service
    healthcheck:
      test: "curl --fail --silent localhost:5000//api/health_check | grep OK || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
    depends_on:
      - ldap-service
    links:
      - ldap-service
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    ports:
      - 5000:5000
    restart: always
    networks:
      - bridge-network
    volumes:
      - /Users/stevemitchell/Development/python_projects/ldap_load_testing/configs/gateway-service.yml:/etc/gateway_service/config.yaml

  ldap-service:
    build:
      context: ldap-service
    healthcheck:
      test: "curl --fail --silent localhost:5002//api/health_check | grep OK || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
    depends_on:
      - openldap-server
    links:
      - openldap-server
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    ports:
      - 5002:5002
      - 9100:9100
    restart: always
    networks:
      - bridge-network
    volumes:
      - /Users/stevemitchell/Development/python_projects/ldap_load_testing/configs/ldap-service.yml:/etc/ldap_service/config.yaml

volumes:
  ldap_data:
  ldap_config:
